#!/usr/bin/env python3
"""
Offscript ad — music bed + sound design, synthesised from scratch.

Why synthesised: the brief requires a licence that is unambiguous for paid
advertising. Everything here is generated by this script (no samples, no
third-party material), so the rights sit entirely with whoever owns this
repository. Deterministic: fixed RNG seeds, same bytes on every run.

Output (48 kHz, 16-bit stereo WAV) → public/ad/audio/
  music-main.wav (30 s)  music-short.wav (15 s)
  sfx-*.wav (short one-shots, placed by src/ad/AdAudio.tsx)

Musical frame: 120 BPM (one beat = 15 frames at 30 fps, one bar = 2 s), so
every scene boundary of the film falls on a beat.
"""
import os
import numpy as np
from scipy import signal
from scipy.io import wavfile

SR = 48000
BPM = 120
BEAT = 60 / BPM
BAR = 4 * BEAT
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'public', 'ad', 'audio')
os.makedirs(OUT, exist_ok=True)


# --------------------------------------------------------------------------- utils
def t_axis(dur):
    return np.arange(int(round(dur * SR))) / SR


def midi(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def lowpass(x, fc, order=2):
    b, a = signal.butter(order, min(fc / (SR / 2), 0.99), 'low')
    return signal.lfilter(b, a, x, axis=0)


def highpass(x, fc, order=2):
    b, a = signal.butter(order, fc / (SR / 2), 'high')
    return signal.lfilter(b, a, x, axis=0)


def bandpass_sweep(noise, f0, f1, q=1.2, steps=64):
    """time-varying band-pass by block processing with a cross-faded sweep"""
    n = len(noise)
    out = np.zeros(n)
    edges = np.linspace(0, n, steps + 1).astype(int)
    for i in range(steps):
        a, b = edges[i], edges[i + 1]
        f = f0 * (f1 / f0) ** ((i + 0.5) / steps)
        lo = max(20, f / (1 + 1 / q))
        hi = min(SR / 2 * 0.98, f * (1 + 1 / q))
        bb, aa = signal.butter(2, [lo / (SR / 2), hi / (SR / 2)], 'band')
        seg = signal.lfilter(bb, aa, noise[max(0, a - 2000):b])
        out[a:b] = seg[-(b - a):]
    return out


def env_adsr(n, a, d, s, r, sustain_len):
    """sample-domain ADSR envelope"""
    A, D, R = int(a * SR), int(d * SR), int(r * SR)
    S = max(0, int(sustain_len * SR))
    e = np.concatenate([
        np.linspace(0, 1, max(A, 1), endpoint=False),
        np.linspace(1, s, max(D, 1), endpoint=False),
        np.full(S, s),
        np.linspace(s, 0, max(R, 1)),
    ])
    if len(e) < n:
        e = np.concatenate([e, np.zeros(n - len(e))])
    return e[:n]


def reverb_ir(dur=2.4, seed=7, bright=6000):
    rng = np.random.default_rng(seed)
    t = t_axis(dur)
    ir = rng.standard_normal((len(t), 2)) * np.exp(-t / (dur / 6.0))[:, None]
    ir = lowpass(ir, bright)
    ir[: int(0.012 * SR)] *= np.linspace(0, 1, int(0.012 * SR))[:, None]
    return ir / np.sqrt((ir ** 2).sum(axis=0))


def convolve_st(x, ir):
    return np.stack([signal.fftconvolve(x[:, c], ir[:, c])[: len(x)] for c in range(2)], axis=1)


def stereo(mono, pan=0.0):
    l = np.cos((pan + 1) * np.pi / 4)
    r = np.sin((pan + 1) * np.pi / 4)
    return np.stack([mono * l, mono * r], axis=1)


def write(name, x, peak_db=-1.0):
    x = np.asarray(x, dtype=np.float64)
    if x.ndim == 1:
        x = stereo(x)
    pk = np.max(np.abs(x)) + 1e-12
    x = x / pk * (10 ** (peak_db / 20))
    wavfile.write(os.path.join(OUT, name), SR, (x * 32767).astype(np.int16))
    print(f'{name:22s} {len(x) / SR:5.2f}s')


# --------------------------------------------------------------------------- music
def saw_voice(freq, dur, harmonics=14, detune_cents=(-7, 0, 7), bright=1.0):
    t = t_axis(dur)
    out = np.zeros(len(t))
    for c in detune_cents:
        f = freq * 2 ** (c / 1200)
        ph = (c + 11) * 0.37  # fixed phase per voice: deterministic
        for k in range(1, harmonics + 1):
            if f * k > 9000:
                break
            out += np.sin(2 * np.pi * f * k * t + ph * k) / k * np.exp(-(k - 1) / (5.5 * bright))
    return out / len(detune_cents)


CHORDS = {
    'Dmaj9': [50, 57, 61, 64, 66, 69],
    'Bm9': [47, 54, 57, 61, 62, 66],
    'Gmaj9': [43, 50, 54, 57, 59, 62],
    'Aadd9': [45, 52, 57, 59, 61, 64],
    'F#m7': [42, 49, 54, 57, 61, 64],
    'Em9': [40, 47, 54, 55, 59, 62],
    'Asus': [45, 52, 57, 59, 62, 64],
}
ROOTS = {'Dmaj9': 38, 'Bm9': 35, 'Gmaj9': 31, 'Aadd9': 33, 'F#m7': 30, 'Em9': 28, 'Asus': 33}


def render_music(total, bars, sections, seed=1):
    """
    bars: list of chord names, one per 2-s bar.
    sections: list of (t0, t1, dict(kick, hats, arp, bass, padlvl, bright, four)) in seconds.
    """
    n = int(total * SR) + SR * 3
    t = np.arange(n) / SR
    pad = np.zeros((n, 2))
    arp = np.zeros((n, 2))
    bass = np.zeros(n)
    drums = np.zeros((n, 2))
    rng = np.random.default_rng(seed)

    def sec_at(x):
        for a, b, p in sections:
            if a <= x < b:
                return p
        return sections[-1][2]

    # pads: one chord per bar, overlapping release so changes glide
    for bi, name in enumerate(bars):
        t0 = bi * BAR
        if t0 >= total:
            break
        p = sec_at(t0 + 0.01)
        dur = BAR + 1.4
        e = env_adsr(int(dur * SR), 0.55, 0.6, 0.82, 1.3, BAR - 1.15)
        for j, note in enumerate(CHORDS[name][1:]):
            v = saw_voice(midi(note), dur, bright=p['bright'])
            v = v * e * (0.9 if j < 2 else 0.7)
            i0 = int(t0 * SR)
            seg = stereo(v, pan=(-0.55, -0.2, 0.15, 0.45, 0.6)[j % 5])
            pad[i0:i0 + len(seg)] += seg[: n - i0] * p['padlvl']

    # gentle filter movement on the pad bus (bright on the hook opening)
    pad = lowpass(pad, 2600)

    # arp: eighth notes through upper chord tones
    eighth = BEAT / 2
    k = 0
    tt = 0.0
    while tt < total:
        p = sec_at(tt)
        if p['arp'] > 0:
            name = bars[min(int(tt / BAR), len(bars) - 1)]
            tones = CHORDS[name][2:]
            seq = tones + tones[-2:0:-1]
            note = seq[k % len(seq)] + 12
            dur = 0.42
            tn = t_axis(dur)
            f = midi(note)
            vel = 0.75 + 0.25 * ((k * 7) % 5) / 4
            v = (np.sin(2 * np.pi * f * tn) + 0.28 * np.sin(4 * np.pi * f * tn)) * np.exp(-tn / 0.13) * vel
            v[: int(0.003 * SR)] *= np.linspace(0, 1, int(0.003 * SR))
            i0 = int(tt * SR)
            seg = stereo(v, pan=0.35 * np.sin(k * 0.9))
            arp[i0:i0 + len(seg)] += seg[: n - i0] * p['arp']
        k += 1
        tt += eighth

    # drums + sub bass, on the beat grid
    kick_env = np.zeros(n)
    beat = 0
    tt = 0.0
    while tt < total:
        p = sec_at(tt)
        i0 = int(tt * SR)
        pos = beat % 4
        if p['kick'] > 0 and (pos in (0, 2) or p.get('four', False)):
            kd = 0.38
            tk = t_axis(kd)
            f = 46 + 70 * np.exp(-tk / 0.035)
            ph = 2 * np.pi * np.cumsum(f) / SR
            kv = np.sin(ph) * np.exp(-tk / 0.16)
            kv[:int(0.002 * SR)] *= np.linspace(0, 1, int(0.002 * SR))
            click = rng.standard_normal(len(tk)) * np.exp(-tk / 0.004) * 0.15
            kv = kv + lowpass(click, 3500)
            lvl = p['kick'] * (1.0 if pos in (0, 2) else 0.7)
            drums[i0:i0 + len(kv)] += stereo(kv * lvl)[: n - i0]
            ke = np.exp(-tk / 0.18) * lvl
            kick_env[i0:i0 + len(ke)] = np.maximum(kick_env[i0:i0 + len(ke)], ke[: n - i0])
        if p['hats'] > 0:
            off = i0 + int(eighth * SR)
            hd = 0.06
            th = t_axis(hd)
            hv = highpass(rng.standard_normal(len(th)), 7000) * np.exp(-th / 0.014) * p['hats']
            drums[off:off + len(hv)] += stereo(hv, pan=0.3)[: max(0, n - off)]
        if p['bass'] > 0 and pos in (0, 2):
            name = bars[min(int(tt / BAR), len(bars) - 1)]
            f = midi(ROOTS[name])
            bd = BEAT * 1.8
            tb = t_axis(bd)
            bv = (np.sin(2 * np.pi * f * tb) + 0.18 * np.sin(4 * np.pi * f * tb)) * env_adsr(len(tb), 0.012, 0.2, 0.75, 0.25, bd - 0.5)
            bass[i0:i0 + len(bv)] += bv[: n - i0] * p['bass']
        beat += 1
        tt += BEAT

    duck = 1 - 0.45 * np.clip(kick_env, 0, 1)
    pad *= duck[:, None]
    bass *= duck

    ir = reverb_ir(2.6, seed=11)
    wet = convolve_st(pad * 0.5 + arp * 0.8, ir)
    mix = pad * 0.55 + arp * 0.55 + wet * 0.42 + stereo(lowpass(bass, 180)) * 0.85 + drums * 0.62
    mix = highpass(mix, 28)
    # very light saturation only on the loudest peaks — keeps the arrangement's
    # dynamics (calm benefit scene vs. full production scene) intact
    pk = np.max(np.abs(mix)) + 1e-12
    mix = np.tanh(mix / pk * 1.15) / np.tanh(1.15) * pk
    end = int(total * SR)
    mix = mix[: end + int(0.0 * SR)]
    # fade-in 0.05 s, tail fade over the last 0.9 s
    fi = int(0.05 * SR)
    mix[:fi] *= np.linspace(0, 1, fi)[:, None]
    fo = int(0.9 * SR)
    mix[-fo:] *= np.linspace(1, 0, fo)[:, None] ** 1.5
    return mix


def P(kick=0, hats=0, arp=0, bass=0, padlvl=1.0, bright=1.0, four=False):
    return dict(kick=kick, hats=hats, arp=arp, bass=bass, padlvl=padlvl, bright=bright, four=four)


main_bars = ['Dmaj9', 'Dmaj9', 'Bm9', 'Gmaj9', 'Aadd9', 'Dmaj9', 'Bm9', 'Gmaj9',
             'Aadd9', 'F#m7', 'Gmaj9', 'Em9', 'Asus', 'Dmaj9', 'Dmaj9']
main_sections = [
    (0.0, 3.0, P(arp=0.26, padlvl=0.75, bright=0.9)),                      # hook
    (3.0, 6.0, P(arp=0.22, bass=0.5, padlvl=0.8)),                          # problem
    (6.0, 10.0, P(kick=0.75, arp=0.36, bass=0.9, padlvl=0.9, bright=1.1)),  # solution
    (10.0, 16.0, P(kick=0.85, hats=0.22, arp=0.42, bass=1.0, bright=1.2, four=True)),  # process
    (16.0, 21.0, P(kick=0.8, hats=0.16, arp=0.36, bass=1.0, bright=1.1)),   # proof
    (21.0, 25.0, P(arp=0.16, bass=0.4, padlvl=0.6)),                        # benefit: rest
    (25.0, 27.0, P(kick=0.6, arp=0.3, bass=0.8, padlvl=1.0, bright=1.1)),   # CTA lands
    (27.0, 31.0, P(arp=0.12, padlvl=0.7)),                                  # CTA holds
]
short_bars = ['Dmaj9', 'Bm9', 'Gmaj9', 'Aadd9', 'F#m7', 'Asus', 'Dmaj9', 'Dmaj9']
short_sections = [
    (0.0, 3.0, P(arp=0.30, padlvl=0.9, bright=0.9)),
    (3.0, 6.0, P(kick=0.75, arp=0.36, bass=0.9, bright=1.1)),
    (6.0, 10.5, P(kick=0.85, hats=0.2, arp=0.42, bass=1.0, bright=1.2, four=True)),
    (10.5, 12.5, P(kick=0.6, arp=0.3, bass=0.8, padlvl=1.0)),
    (12.5, 16.0, P(arp=0.18, padlvl=0.9)),
]

# --------------------------------------------------------------------------- sfx
rng = np.random.default_rng(42)


def sfx_open():
    d = 0.95
    t = t_axis(d)
    nz = rng.standard_normal(len(t))
    sw = bandpass_sweep(nz, 500, 5200, q=1.6)
    e = np.clip(t / 0.62, 0, 1) ** 2.2 * np.exp(-np.clip(t - 0.62, 0, None) / 0.09)
    air = sw * e
    bloom = np.sin(2 * np.pi * 62 * t) * np.exp(-np.clip(t - 0.62, 0, None) / 0.2) * (t > 0.6)
    return np.stack([air * 0.9 + bloom * 0.5, air * 0.75 + bloom * 0.5], axis=1)


def sfx_thump(f0=90, f1=52, d=0.55, click=0.12):
    t = t_axis(d)
    f = f1 + (f0 - f1) * np.exp(-t / 0.05)
    v = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.15)
    v += lowpass(rng.standard_normal(len(t)) * np.exp(-t / 0.006), 2500) * click
    v[: int(0.002 * SR)] *= np.linspace(0, 1, int(0.002 * SR))
    return v


def sfx_whoosh(f0=3200, f1=700, d=0.62, peak=0.28, pan_sweep=0.0):
    t = t_axis(d)
    sw = bandpass_sweep(rng.standard_normal(len(t)), f0, f1, q=1.3)
    e = np.where(t < peak, (t / peak) ** 2, np.exp(-(t - peak) / 0.12))
    v = sw * e
    pan = np.linspace(-pan_sweep, pan_sweep, len(t))
    return np.stack([v * np.cos((pan + 1) * np.pi / 4), v * np.sin((pan + 1) * np.pi / 4)], axis=1)


def sfx_tick(f=2200, d=0.12):
    t = t_axis(d)
    v = (np.sin(2 * np.pi * f * t) + 0.35 * np.sin(2 * np.pi * f * 1.5 * t)) * np.exp(-t / 0.022)
    v[: int(0.001 * SR)] *= np.linspace(0, 1, int(0.001 * SR))
    return v


def sfx_place():
    t = t_axis(0.35)
    v = np.sin(2 * np.pi * 210 * t) * np.exp(-t / 0.07)
    v += lowpass(rng.standard_normal(len(t)) * np.exp(-t / 0.012), 1800) * 0.4
    return v


def bell(freqs, d, decay, amps=None):
    t = t_axis(d)
    v = np.zeros(len(t))
    amps = amps or [1.0] * len(freqs)
    for f, a in zip(freqs, amps):
        for ratio, ra, rd in ((1, 1.0, 1.0), (2.756, 0.32, 0.55), (5.404, 0.12, 0.3)):
            v += a * ra * np.sin(2 * np.pi * f * ratio * t) * np.exp(-t / (decay * rd))
    v[: int(0.004 * SR)] *= np.linspace(0, 1, int(0.004 * SR))
    return v


def sfx_reveal():
    d = 1.4
    t = t_axis(d)
    sh = np.zeros(len(t))
    for i, n in enumerate([74, 78, 81, 85]):
        f = midi(n) * (1 + 0.0015 * (i - 1.5))
        sh += np.sin(2 * np.pi * f * t) * np.exp(-t / 0.55) * (0.9 - i * 0.12)
    sheen = highpass(rng.standard_normal(len(t)), 6000) * np.exp(-t / 0.25) * 0.08
    low = np.sin(2 * np.pi * midi(38) * t) * np.exp(-t / 0.35) * 0.7
    v = sh * 0.5 + sheen + low
    v[: int(0.006 * SR)] *= np.linspace(0, 1, int(0.006 * SR))
    ir = reverb_ir(1.6, seed=3, bright=8000)
    st = stereo(v)
    return st * 0.7 + convolve_st(st, ir) * 0.35


def sfx_team():
    d = 1.6
    t = t_axis(d)
    v = np.zeros(len(t))
    for n in (62, 66, 69, 73):
        v += np.sin(2 * np.pi * midi(n) * t) * (1 - np.exp(-t / 0.03)) * np.exp(-t / 0.7)
    st = stereo(v * 0.4)
    return st * 0.7 + convolve_st(st, reverb_ir(1.8, seed=5)) * 0.4


def sfx_figure():
    t = t_axis(0.9)
    v = (np.sin(2 * np.pi * midi(50) * t) + 0.4 * np.sin(2 * np.pi * midi(62) * t)) * (1 - np.exp(-t / 0.01)) * np.exp(-t / 0.32)
    return v


def sfx_riser():
    d = 1.0
    t = t_axis(d)
    f = 180 * (900 / 180) ** (t / d)
    tone = np.sin(2 * np.pi * np.cumsum(f) / SR) * 0.25
    nz = bandpass_sweep(rng.standard_normal(len(t)), 600, 6000, q=1.4) * 0.8
    e = (t / d) ** 2.4
    e[-int(0.015 * SR):] *= np.linspace(1, 0, int(0.015 * SR))
    return (tone + nz) * e


def sfx_cta():
    st = stereo(bell([midi(74), midi(81)], 2.0, 0.6, [1.0, 0.6]) * 0.6)
    return st * 0.75 + convolve_st(st, reverb_ir(2.2, seed=9, bright=7000)) * 0.45


if __name__ == '__main__':
    write('music-main.wav', render_music(30.0, main_bars, main_sections, seed=1), peak_db=-3.0)
    write('music-short.wav', render_music(15.0, short_bars, short_sections, seed=2), peak_db=-3.0)
    write('sfx-open.wav', sfx_open(), -3)
    write('sfx-land.wav', sfx_thump(), -4)
    write('sfx-move.wav', sfx_whoosh(), -6)
    write('sfx-turn.wav', sfx_whoosh(2400, 900, 0.7, 0.3, pan_sweep=0.6), -6)
    write('sfx-pop.wav', sfx_tick(1500, 0.1), -10)
    write('sfx-tick.wav', sfx_tick(), -9)
    write('sfx-place.wav', sfx_place(), -6)
    write('sfx-reveal.wav', sfx_reveal(), -3)
    write('sfx-team.wav', sfx_team(), -5)
    write('sfx-figure.wav', sfx_figure(), -6)
    write('sfx-riser.wav', sfx_riser(), -6)
    write('sfx-impact.wav', sfx_thump(80, 40, 0.7, 0.18), -3)
    write('sfx-cta.wav', sfx_cta(), -4)
