#!/usr/bin/env python3
"""
Generates OFFSCRIPT's entire sound-design library from scratch — plain sine
synthesis, additive harmonics, and FFT-band-limited noise, all pure numpy.
No sampled or licensed audio of any kind goes in, and nothing here is a
copy of an Apple system sound (Apple is a QUALITY reference only, per the
brief) — every waveform is generated by the math below.

Seven files, matching the seven-sound library the motion system is scored
to: SCROLL_AIR, FLIP_AIR, MORPH_TONE, SOFT_SETTLE, ICON_LOCK, three
METRIC_PULSE variants, and the OFFSCRIPT_SIGNATURE closing sound. Re-run
this script any time the motion timing changes enough to want re-tuned
sounds; it always writes into public/sfx/.
"""
import numpy as np
import wave
import os

SR = 44100
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "public", "sfx")


def envelope(n, points):
    """points: list of (fraction 0-1, amplitude 0-1) — piecewise-linear."""
    xs = np.array([p[0] for p in points]) * (n - 1)
    ys = np.array([p[1] for p in points])
    return np.interp(np.arange(n), xs, ys)


def sine(freq, n, sr=SR, phase=0.0):
    t = np.arange(n) / sr
    return np.sin(2 * np.pi * freq * t + phase)


def sine_sweep(f0, f1, n, sr=SR):
    t = np.arange(n) / sr
    dur = n / sr
    # linear frequency sweep via integrated instantaneous phase
    k = (f1 - f0) / max(dur, 1e-9)
    phase = 2 * np.pi * (f0 * t + 0.5 * k * t ** 2)
    return np.sin(phase)


def band_noise(n, low, high, sr=SR, seed=None):
    rng = np.random.default_rng(seed)
    noise = rng.standard_normal(n)
    spec = np.fft.rfft(noise)
    freqs = np.fft.rfftfreq(n, d=1 / sr)
    mask = (freqs >= low) & (freqs <= high)
    spec = spec * mask
    filtered = np.fft.irfft(spec, n)
    peak = np.max(np.abs(filtered)) + 1e-9
    return filtered / peak


def normalize(sig, peak=0.9):
    m = np.max(np.abs(sig)) + 1e-9
    return sig / m * peak


def write_wav(name, sig, sr=SR):
    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, name)
    sig = np.clip(sig, -1.0, 1.0)
    pcm = (sig * 32767).astype(np.int16)
    with wave.open(path, "w") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(sr)
        f.writeframes(pcm.tobytes())
    print(f"  {name}  ({len(sig)/sr*1000:.0f}ms)")


# ---------------------------------------------------------------------------
# 1. SCROLL AIR — a soft broadband air sweep. Starts a hair before the
#    visible movement (this file itself starts at the "air" onset; the
#    caller places it 2-4 frames ahead of the motion in the timeline),
#    swells to its peak in the middle (max velocity), then a long soft
#    decay with a subtle upward tonal cue right at the overshoot moment,
#    settling to near-silence by the snap-to-0 frame.
# ---------------------------------------------------------------------------
def make_scroll_air():
    dur = 0.62
    n = int(dur * SR)
    air = band_noise(n, 500, 3200, seed=1)
    amp = envelope(n, [(0, 0), (0.12, 0.55), (0.42, 1.0), (0.72, 0.32), (0.85, 0.16), (1.0, 0.0)])
    sig = air * amp
    # subtle tonal cue right at the overshoot point (~78% through)
    cue_start = int(0.74 * n)
    cue_n = int(0.10 * n)
    cue = sine_sweep(900, 760, cue_n) * envelope(cue_n, [(0, 0), (0.3, 1), (1, 0)]) * 0.14
    sig[cue_start:cue_start + cue_n] += cue
    write_wav("scroll-air.wav", normalize(sig, 0.55))


# ---------------------------------------------------------------------------
# 2. FLIP AIR — a tighter, higher whoosh whose intensity follows rotation
#    speed (fast rise, fast fall around the midpoint of the flip), a small
#    tonal shift right at the overshoot, and a quiet settle click at 0deg.
# ---------------------------------------------------------------------------
def make_flip_air():
    dur = 0.40
    n = int(dur * SR)
    air = band_noise(n, 900, 4200, seed=2)
    # rotation speed peaks near the middle of the flip (edge-on point)
    amp = envelope(n, [(0, 0), (0.22, 0.5), (0.48, 1.0), (0.68, 0.4), (0.85, 0.12), (1.0, 0.0)])
    sig = air * amp
    tone_start = int(0.60 * n)
    tone_n = int(0.14 * n)
    tone = sine_sweep(1100, 880, tone_n) * envelope(tone_n, [(0, 0), (0.25, 1), (1, 0)]) * 0.16
    sig[tone_start:tone_start + tone_n] += tone
    # quiet settle click at the very end (short high click, tiny amplitude)
    click_n = int(0.02 * SR)
    click_start = n - click_n - int(0.01 * SR)
    click = sine(2200, click_n) * envelope(click_n, [(0, 0), (0.1, 1), (1, 0)]) * 0.10
    sig[click_start:click_start + click_n] += click
    write_wav("flip-air.wav", normalize(sig, 0.5))


# ---------------------------------------------------------------------------
# 3. MORPH TONE — the quietest, softest sound in the library: a single sine
#    pad gliding a few Hz downward under a blur/scale crossfade, never
#    percussive, just a wash under the visual dissolve.
# ---------------------------------------------------------------------------
def make_morph_tone():
    dur = 0.34
    n = int(dur * SR)
    tone = sine_sweep(420, 360, n) + 0.3 * sine_sweep(840, 720, n)
    amp = envelope(n, [(0, 0), (0.3, 1), (0.7, 0.85), (1, 0)])
    sig = tone * amp
    write_wav("morph-tone.wav", normalize(sig, 0.32))


# ---------------------------------------------------------------------------
# 4. SOFT SETTLE — the generic "landed" sound for hero-shape settles and
#    camera pushes: a low, soft thump, quick attack, gentle decay, no click.
# ---------------------------------------------------------------------------
def make_soft_settle():
    dur = 0.26
    n = int(dur * SR)
    body = sine(165, n) + 0.4 * sine(110, n)
    amp = envelope(n, [(0, 0), (0.05, 1), (0.4, 0.5), (1, 0)])
    sig = body * amp
    write_wav("soft-settle.wav", normalize(sig, 0.5))


# ---------------------------------------------------------------------------
# 5. ICON LOCK — a clean, short tonal ping (glass-tick character) that
#    plays exactly on an icon's completion-overshoot frame. Two harmonics,
#    fast decay, nothing sustained.
# ---------------------------------------------------------------------------
def make_icon_lock():
    dur = 0.16
    n = int(dur * SR)
    tone = sine(1250, n) + 0.5 * sine(2500, n) + 0.2 * sine(3750, n)
    amp = envelope(n, [(0, 0), (0.03, 1), (0.35, 0.25), (1, 0)])
    sig = tone * amp
    write_wav("icon-lock.wav", normalize(sig, 0.42))


# ---------------------------------------------------------------------------
# 6. METRIC PULSE — three distinct variants, one per stat, each reading as
#    part of the same family but individually identifiable: soft low pulse,
#    a slightly stronger tonal pulse, and a "resolving" pulse with a subtle
#    high harmonic on top for the close of the sequence. No counter-tick,
#    no casino chime — single soft events, not a chattering loop.
# ---------------------------------------------------------------------------
def make_metric_pulses():
    dur = 0.17
    n = int(dur * SR)
    amp = envelope(n, [(0, 0), (0.08, 1), (0.5, 0.35), (1, 0)])

    pulse1 = sine(210, n) * amp
    write_wav("metric-pulse-1.wav", normalize(pulse1, 0.4))

    pulse2 = (sine(340, n) + 0.35 * sine(680, n)) * amp
    write_wav("metric-pulse-2.wav", normalize(pulse2, 0.45))

    dur3 = 0.21
    n3 = int(dur3 * SR)
    amp3 = envelope(n3, [(0, 0), (0.08, 1), (0.45, 0.4), (1, 0)])
    shimmer = sine(1900, n3) * envelope(n3, [(0, 0), (0.5, 0), (0.6, 1), (1, 0)]) * 0.25
    pulse3 = (sine(460, n3) + 0.3 * sine(920, n3)) * amp3 + shimmer
    write_wav("metric-pulse-3.wav", normalize(pulse3, 0.48))


# ---------------------------------------------------------------------------
# 7. OFFSCRIPT SIGNATURE — the film's single strongest sonic moment, for the
#    final logo reveal only. A low harmonic swell plus a thin air layer
#    during the line's transformation into the logo, then a soft low impact
#    the instant the logo is fully visible, then one clean short high
#    harmonic — and after that, nothing: the logo holds in silence.
# ---------------------------------------------------------------------------
def make_offscript_signature():
    swell_dur = 0.62
    swell_n = int(swell_dur * SR)
    fundamental = 90
    swell = (
        sine(fundamental, swell_n)
        + 0.5 * sine(fundamental * 2, swell_n)
        + 0.25 * sine(fundamental * 3, swell_n)
    )
    swell_amp = envelope(swell_n, [(0, 0), (0.55, 0.7), (1, 1.0)])
    air = band_noise(swell_n, 300, 2200, seed=3) * envelope(swell_n, [(0, 0), (0.4, 0.12), (1, 0.22)])
    swell_sig = swell * swell_amp * 0.55 + air

    impact_dur = 0.22
    impact_n = int(impact_dur * SR)
    impact = sine(70, impact_n) + 0.4 * sine(140, impact_n)
    impact_amp = envelope(impact_n, [(0, 0), (0.02, 1), (0.5, 0.2), (1, 0)])
    impact_sig = impact * impact_amp * 0.85

    harmonic_dur = 0.30
    harmonic_n = int(harmonic_dur * SR)
    harmonic = sine(2100, harmonic_n) + 0.4 * sine(3150, harmonic_n)
    harmonic_amp = envelope(harmonic_n, [(0, 0), (0.04, 1), (0.4, 0.3), (1, 0)])
    harmonic_sig = harmonic * harmonic_amp * 0.28

    silence_n = int(0.35 * SR)

    total_n = swell_n + impact_n + silence_n
    sig = np.zeros(total_n)
    sig[:swell_n] += swell_sig
    impact_start = swell_n - int(0.03 * SR)
    sig[impact_start:impact_start + impact_n] += impact_sig
    harm_start = impact_start + int(0.03 * SR)
    end = min(harm_start + harmonic_n, total_n)
    sig[harm_start:end] += harmonic_sig[: end - harm_start]

    write_wav("offscript-signature.wav", normalize(sig, 0.7))


if __name__ == "__main__":
    print("Synthesizing OFFSCRIPT sound-design library into public/sfx/ ...")
    make_scroll_air()
    make_flip_air()
    make_morph_tone()
    make_soft_settle()
    make_icon_lock()
    make_metric_pulses()
    make_offscript_signature()
    print("Done — 8 files (7 sounds, metric-pulse has 3 variants).")
